Game finishing
gii-is-DP1/DP1--2023-2024-l3-1 pull request #126
Opened 2024-01-14 02:37 UTC by javnievic

2024-01-14 12:20 UTC, ferferga requested changes

2024-01-14 18:28 UTC, ferferga commented on frontend/src/pages/player/GamePage.jsx
> +        /*if (game.status === GameStatus.FINISHED) {
Esto si hay que eliminarlo, fuera.

2024-01-14 18:28 UTC, ferferga commented on frontend/src/pages/player/GamePage.jsx
> +        if (!message && error ) {
```suggestion
        if (!message && error) {
```

2024-01-14 18:28 UTC, ferferga commented on src/main/java/org/springframework/samples/petclinic/services/GameService.java
> +                Boolean gameFinished = gp.getCurrentCard().get().equals(gp.getCards().get(gp.getCards().size()-1));
No entiendo muy bien esto, que tienen que ver las cartas de un solo jugador con que finalice el juego?

2024-01-15 01:43 UTC, javnievic commented on src/main/java/org/springframework/samples/petclinic/services/GameService.java
> +                Boolean gameFinished = gp.getCurrentCard().get().equals(gp.getCards().get(gp.getCards().size()-1));
Pq si la carta que tiene es la última de su mano, al estar en el if de que ha acertado, si es la última carta hace que el juego acabe

2024-01-15 12:39 UTC, Joserra24 approved these changes

2024-01-15 12:41 UTC, merged