Css changes and H1-H26
gii-is-DP1/DP1--2023-2024-l3-1 pull request #98
Opened 2023-11-27 23:02 UTC by javnievic

2023-11-29 11:50 UTC, ferferga requested changes
Buena plantilla para usar de base 👍

2023-11-29 11:50 UTC, ferferga commented on frontend/src/components/player/PlayPage.jsx
> +            </Link>
```suggestion
            <Link to={"join"}>
                <DButton className="button">Unirse a partida</button>   
            </Link>
```

La tabulación y DButton!

2023-11-29 11:50 UTC, ferferga commented on frontend/src/components/player/PlayPage.jsx
> +            <button className="button">Crear partida</button>
```suggestion
            <DButton className="button">Crear partida</DButton>
```

2023-11-29 11:50 UTC, ferferga commented on frontend/src/static/css/play/playPage.css
> +
```suggestion
```

2023-11-30 16:42 UTC, ferferga requested changes

2023-11-30 16:42 UTC, ferferga commented on frontend/src/components/player/PlayPage.jsx
> +    */
```suggestion
    backgroundColor: 'white';
    color: 'black';
    padding: '8px 40px';
    margin: '40px';
    border: '1px solid #ccc';
    borderRadius: '15px';
```

2023-11-30 16:42 UTC, ferferga commented on frontend/src/components/player/PlayPage.jsx
> +export const inputStyles = {
```suggestion
const lobbyButtonStyle = {
```

2023-11-30 16:42 UTC, ferferga commented on frontend/src/components/player/PlayPage.jsx
> +            <DButton className="button">Crear partida</DButton>
```suggestion
            <DButton style={lobbyButtonStyle}>Crear partida</DButton>
```

2023-11-30 16:42 UTC, ferferga commented on frontend/src/components/player/PlayerProfile.jsx
> +            <img
Lo que has hecho aquí es lo que tenías que hacer arriba que te he dicho por WhatsApp

2023-11-30 16:42 UTC, ferferga commented on frontend/src/static/css/play/playPage.css
> +  }
```suggestion
```

2023-11-30 16:42 UTC, ferferga commented on frontend/src/components/player/GameJoinPage.jsx
> +
```suggestion
        </div>
    );
```

2023-12-03 18:43 UTC, javnievic commented on frontend/src/components/player/PlayerProfile.jsx
> +            <img
No me acuerdo, que es lo que te refieres?

2023-12-03 19:28 UTC, merged